### ISSUE TITLE
Password change does not update actual password

### ISSUE THREAD

**Issue by krispopat** [ox-it/ords-ui#1]
On the user profile page entering a new password and submitting has no effect.

**Comment by thestoat** [comment]
This will change the ODBC password for the user on their databases, not the profile password since that is managed by SSO. Are you saying the ODBC password doesn't get changed?

**Comment by krispopat** [comment]
I think this issue is probably isolated to the ords2 ui ;)

**Comment by thestoat** [comment]
Ah :-) I'll relax then

**Comment by scottbw** [comment]
Yep, in ORDS2 we can have either SSO-based authentication as used at Oxford, or it can handle regular logins using a username and password. The password change UI is just for the latter case.

**Comment by scottbw** [comment]
@kris did you rebuild and redeploy the User API? Its working fine on my installation.

**Comment by krispopat** [comment]
I've updated the user api and this seems to work okay now on both my local installation and on the test server, so closing for now.
