### ISSUE TITLE
Data editing interface: Can't select valid data from drop-down/autocompete lists

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords-ui#10]
When a user edits the data in a field that links to another table, they can only select from records already added to that related table. This is generally necessary to retain the integrity of the database. To prevent a user adding an invalid value, the old system presented either a drop-down list of values (if there were fewer than about 20 to choose between) or used an auto-completion system (if there were more than 20 or so values to choose between). i.e.
![ords_dropdownexample](https://cloud.githubusercontent.com/assets/11886974/12980481/7e59b022-d0d4-11e5-88c8-c8c4a1bb1b18.png)

Without this functionality users will keep trying to add invalid data.

**Comment by krispopat** [comment]
Update on server for this, for checking

**Comment by scottbw** [comment]
Looks good; fixed a few issues but now works well.
