### ISSUE TITLE
Data Editing page: Filters don't offer less than or greater than options for numeric fields

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords-ui#12]
At present, the filter functionality on the data editing page enables the following criteria: is; is not; like; contains; isNULL. This is fine for strings, but where the filter is being applied to a numeric field these are not so appropriate. 'Less than' and 'greater than' options should also be included.

**Comment by jajwilson** [comment]
Looking again at the current Oxford ORDS I realized that it would also be good to have an 'is not NULL' option as well, for when people want to sort results.

**Comment by scottbw** [comment]
Functionality restored
