### ISSUE TITLE
Project Details: Date fields don't actually seem to be of the 'date' data type

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords-ui#16]
There is no sanity check on the dates fields - I managed to assign a project end date of 45/3/201. This suggest to me that they're not actually date fields at all. In the original ORDS we included a date-picker function, enabling users to either type in a valid date by hand or pick one from a calendar.

**Comment by scottbw** [comment]
In ORDS1 these are all stored as Strings for some reason, and converted back and forth from the real dates you get in the UI. We'll do the same for now.

**Comment by scottbw** [comment]
Made into standard Date fields, and formatted using Angular Date filters; the browser should show a date picker for these fields when editing or creating new projects.

**Comment by scottbw** [comment]
Bah, I see Firefox still doesn't use input type="date" properly. Have added a validator as a fallback for older browsers.
