### ISSUE TITLE
Data Editing Interface: Cannot add additional filters

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords-ui#19]
The filtering interface is now super responsive, which is great, but one can no longer add more than one filter. It used to be the case that the user could build a complex filter by adding additional criteria using AND/OR. e.g.
![ords_complexfilter](https://cloud.githubusercontent.com/assets/11886974/12982035/2981667e-d0db-11e5-970e-4d7b10d4191b.png)

**Comment by scottbw** [comment]
Filter interface restored to its previous functionality
