### ISSUE TITLE
Data size for uploaded database not showing

### ISSUE THREAD

**Issue by krispopat** [ox-it/ords-ui#2]
On the databases page the size of the original uploaded database file should be shown.

**Comment by scottbw** [comment]
I don't think its ever being set on upload; the API correctly returns 0, which is the value in the record.

**Comment by krispopat** [comment]
Yes, I think you are correct, I'll fix and test again

**Comment by krispopat** [comment]
I've fixed this and it works for me, but would value someone else trying it to make sure before I close the issue.

**Comment by scottbw** [comment]
Have you committed that Kris? I can't see any changes in database-api.

**Comment by scottbw** [comment]
Fixed; also formatted it more nicely.
