### ISSUE TITLE
Enabling project creation

### ISSUE THREAD

**Issue by asimong** [ox-it/ords-ui#23]
When initially registering as a user, before e-mail confirmation is done, it appeared possible to start a new project. However, after filling in the form, it was refused, thus wasting effort. Would it be possible only to enable access to the project creation form after e-mail confirmation has been completed? Maybe if the button is clicked, just respond with a message like "e-mail must first be confirmed before creating a project" or something, to avoid this minor frustration.

Thanks

**Comment by scottbw** [comment]
Fixed for unverified users  - i.e. full users who need to confirm email. Not for users who are confirmed but don't have permissions.
