### ISSUE TITLE
Account logged in, verified, trying to create a project fails

### ISSUE THREAD

**Issue by jamescummings** [ox-it/ords-ui#27]
My account is logged in, verified, etc. but when I try to create a project I don't seem to have the requisite permissions.

Specifically it says:

> You are not authorised to do that. The action you have just tried to perform requires a higher permission level than the one you currently have for this project. If you believe you should be able to perform this action, please contact the project owner to discuss adjusting your permissions.

**Comment by scottbw** [comment]
Fixed.
