### ISSUE TITLE
Rebranding to trunkdb

### ISSUE THREAD

**Issue by jamescummings** [ox-it/ords-ui#28]
If the software is rebranding to trunkdb then all the mention of ORDS should change, and various institutional specific text, and the mentions of ords@it.ox.ac.uk in help messages, etc.

**Comment by MerielP** [comment]
On a similar note, some of the help text contains links to Oxford's ORDS documentation.

**Comment by scottbw** [comment]
Underway... still need to port info from Oxfords' help pages into the app

**Comment by scottbw** [comment]
Online Help pages is now a separate bug
