### ISSUE TITLE
Unhelpful error message when adding project start/end dates via Firefox

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#34]
I'm in the process of creating a new project in Firefox. When I start typing in the 'Start date' field, I get a pop-up error message saying 'You need to provide a valid date'.

This is somewhat irritating, as it appears whenever anything is typed in the field, even if it's the start of a valid date: it would be better if the message didn't appear until the user tried to navigate away from the field. 

However, what's more of a problem is that it doesn't give any indication of what a valid date is - trial and error reveals that it will accept dates in the format YYYY-MM-DD (but not, for example, DD/MM/YYYY), but the error message doesn't tell you that.

While it's pernickety about the format, it seems less bothered about the actual numbers. I've just entered 1800-77-56 as the project end date, and it quite happily let me save this (and didn't seem troubled by the fact that the end date was before the start date). When I went back to the project details page, I found that the system had silently 'corrected' the date, and it was now displaying as 1806-06-25. While I think I see what's going on here, it's not very helpful: it would be much preferable to flag up the fact that it's not a valid date and let the user correct it before saving.

I notice that if one creates a project in Chrome, there's a date picker - which, somewhat inconsistently, presents the date in the DD/MM/YYYY format.

**Comment by MerielP** [comment]
Something similar also happens with the 'Created on' field on the 'Add Database to Project'/'Edit Database Details' form, except there there's no error message: the 'Add' button is just greyed out until the right format is given - which could be very confusing if one didn't realize the problem was the wrong date format.

In ORDS1, while there was a date picker for this field, it would also accept free text. I believe this was a deliberate choice: if users were uploading a copy of a database that had been created some time earlier, they might not know the precise date of creation, and so might wish to type just a year, a range, or even something like 'In the mid 1990s'. (Though an easy workround for this would be to leave the date field blank, and put the information in the description.)

**Comment by scottbw** [comment]
We removed the bespoke picker and use the HTML5 standard control - sadly some browsers implement it with more or less useful outcomes.

(I think for Chrome the date order comes from the locale set on the computer itself - on mine it uses dd/mm/yyyy.)

I guess we can just make this free text instead for now as its not used for actually calculating any dates or durations.

**Comment by scottbw** [comment]
Fixed in Dev with switch back to free text.
