### ISSUE TITLE
After creating a new database, you're taken back to the project page

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#35]
When you fill in the 'Add Database to Project' form and click 'Add', you find yourself back on the project page, and then have to click the name of the database to get to the database page. While not a big thing, this does add an extra (and seemingly unnecessary) step to the process. If you had a long list of databases in the project, it could be quite annoying to have to hunt through them to track down the one you've just created.

**Comment by scottbw** [comment]
Agreed, this is irritating - we're trying to cut down on the amount of clicking around needed

**Comment by scottbw** [comment]
Fixed in Dev; on create navigates to new db view
