### ISSUE TITLE
Paragraph breaks not displaying in database metadata

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#37]
If one adds multiple paragraphs of text to the 'Database description' field (or to the 'Data sources' and 'Data gathering process' fields), the paragraph breaks will not display on the database page.

The paragraph breaks are obviously being recorded, as they appear when one goes back to look at the 'Edit Database Details' form - but not anywhere else.

**Comment by scottbw** [comment]
Fixed in Dev: descriptive fields now styled with visible breaks
