### ISSUE TITLE
Unclear whether newly created projects have trial status

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#39]
When one completes the 'Create New Project' form, the text at the top claims the project will be a trial one. It's also labelled as such in the project list.

However, there's no obvious way of requesting that a project be upgraded to full status. It's not even clear that the project really does have trial status: I've just successfully created a dataset, which one isn't supposed to be able to do with a trial project.

So either the text claiming it's a trial project needs removing, or the distinction between the two (and a method for requesting an upgrade) needs to be re-implemented.

**Comment by scottbw** [comment]
The whole "trial" vs "full" issue is one aspect of the service model discussions we're having at the moment.

**Comment by scottbw** [comment]
Trial project wording removed. Restrictions are based on user type rather than projects.
