### ISSUE TITLE
Data Viewer doesn't deal well with long text fields

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#40]
When a table is viewed in the Data Viewer, the width of the columns adapts to fit the size of the window. However, the white cells which contain the data don't adjust, and there seems to be no way of resizing them to accommodate longer text strings. This results in a lot of data that's cannot be seen without clicking in individual cells:

![long text fields in data viewer](https://cloud.githubusercontent.com/assets/13660306/18922943/79dc2f7e-85a2-11e6-82b7-453b71211e8b.PNG)

**Comment by scottbw** [comment]
HTML5 has dropped the resize attribute for inputs - it now only works for textarea elements :(

**Comment by scottbw** [comment]
Replacing the input elements with textareas means you can resize them as required:

<img width="1357" alt="textareas" src="https://cloud.githubusercontent.com/assets/443092/19077786/d35791cc-8a45-11e6-8697-556d0dd97a60.png">

**Comment by MerielP** [comment]
Er, I can now resize fields so that they spill over into (and get hidden behind) other columns... (One of the text boxes in the table pictured below now extends off the right-hand side of the screen.)

![resizeable text areas](https://cloud.githubusercontent.com/assets/13660306/19112957/72bd5d8c-8aff-11e6-8597-71fa47273e86.PNG)

While the ability to resize like this is (apart from this bug) definitely an improvement, I do have a couple of other concerns about it:
- Each field in each record needs to be resized individually. If I've got a table containing a few hundred longish text strings, resizing them all so I can see the contents is going to be a real pain, especially as the resizing doesn't persist if you leave the data viewer and then open the table again
- In ORDS1, the column resizing feature allowed you to make things smaller as well as larger. If you've got a table with a lot of columns each of which contains a short piece of information, it's really handy to be able to reduce the width of the columns so you can get more of them on the screen

**Comment by scottbw** [comment]
Yep, I can see the benefit of resizing the columns... though this is one of those obvious-looking things that is actually really difficult as we have to sync the width changes to each column across 4 tables at once  :)

**Comment by scottbw** [comment]
I have good news and bad news... the good news is that I can get the columns resizing nicely. The bad news is that, for fairly obvious reasons, it means we can't have horizontal scrolling as well.

**Comment by scottbw** [comment]
As you can see, we can easily extend the table by dragging columns out. However, the user then has to scroll the whole window horizontally to see the rest of the table, losing the context of the other controls on the page. This seems pretty much inevitable as constraining the width of the data table in order to make horizontal scrolling also makes resizing the columns a bit futile as the total width can't go up, and the columns can't get much smaller anyway due to the limits on resizing form controls, so you can basically tweak things by a few pixels.

![image](https://cloud.githubusercontent.com/assets/443092/19130973/753ebaec-8b45-11e6-9405-94871daa17e2.png)

**Comment by scottbw** [comment]
D'oh I really shouldn't code when tired ... actually I can just make the wrapper fixed at 100% and that makes a nice scrollbar around the whole table which solves that one.

**Comment by scottbw** [comment]
One marathon coding session later... I think I've cracked it. I'm much happier with the whole Data Viewer UI now - its simpler and cleaner but also more flexible.

**Comment by scottbw** [comment]
Fixed and released - give it a whirl...

**Comment by MerielP** [comment]
Looking good for a lot of tables, but...

I'm getting some misalignment problems in tables with linked fields:

![resizable columns and linked fields](https://cloud.githubusercontent.com/assets/13660306/19306816/5cf825ca-906f-11e6-9462-c249c1c0ea5e.PNG)

If I change the linked field so it displays the ID number rather than the journal name, it behaves better - it just seems to get upset if the content displayed in a linked field is more than a couple of words long:

![resizable columns and linked fields2](https://cloud.githubusercontent.com/assets/13660306/19307037/5712ec66-9070-11e6-961d-38a317ec0ac5.PNG)

Also, the 'Add new row' section isn't properly aligned:

![misaligned add new row section](https://cloud.githubusercontent.com/assets/13660306/19307058/7139e982-9070-11e6-97fe-f2dc41ddc710.PNG)

This seems to happen even in tables without any linked fields. If you make the columns narrower, it's possible to get things a whole column out of step:

![misaligned add new row section2](https://cloud.githubusercontent.com/assets/13660306/19307076/7ef172e8-9070-11e6-917f-34d95464a2df.PNG)

(Screenshots are of Chrome on Windows 7.)

**Comment by scottbw** [comment]
The table is laid out before the linked fields are loaded, so thats probably why they sometimes won't fit. Resizing the columns manually will work though.

If we did resize the table automatically based on the size of the loaded linked field, then I suspect users would end up playing "whack a mole" if they tried to resize them how they wanted, as we'd keep putting them back again whenever the linked values reloaded.

I can't replicate the issue with the "add" form getting out of alignment using Chrome, Safari or FIrefox on Mac -- I'll check it out on Windows 10.

**Comment by MerielP** [comment]
The problem I'm experiencing is that the column _does_ resize when I change which field is being displayed, but the column header doesn't resize to match - so I end up with this sort of thing:

![resizable columns and linked fields3](https://cloud.githubusercontent.com/assets/13660306/19308345/e770e744-9076-11e6-82a7-a39eb9093dd0.PNG)

I wouldn't mind having to resize the column to accommodate the field I was viewing (especially as the resizing seems to persist even if I exit the table and then re-open it, which is great), but ending up with subsequently columns appearing under the wrong field name is not good...

**Comment by scottbw** [comment]
Aha, I think I see what's happening now with those list boxes - they interfere with the overall table column layout.

**Comment by scottbw** [comment]
Right, about a day of esoteric CSS wrangling later:

Option 1: It all works, the drop-downs are the width of the columns. But the column is exactly 2 pixels too wide.

Option 2: It all works, but the table cells can't have borders.

(Its basically a limitation of the Select2 control)

**Comment by scottbw** [comment]
The other issue was caused by the browser not breaking up long words in column headings, so the column with the long name won't shrink in the main view, but it does in the "add" view so they get out of sync. I've added a css fix for that one.

**Comment by scottbw** [comment]
All fixes are live now and ready to retest

**Comment by MerielP** [comment]
The problem with linked fields is now sorted, but I'm still seeing the issue where the 'Add new row' form gets out of step with the rest of the table.

The problem seems to be that the text entry box in each field of the 'Add new row' form always remains the same width, however you resize the columns. The minimum width for columns in the main data table is smaller than this, so shrinking the columns can cause problems - in this screenshot, for example, six columns in the data table occupy the same space as five in the 'Add new row' form, so the text entry box that is directly under the 'notes' heading is actually for the 'provenance' field:

![misaligned add new row section3](https://cloud.githubusercontent.com/assets/13660306/19514724/81ed1930-95ec-11e6-96d0-5b47248fc818.PNG)

If you make a column wider, the columns in the 'Add new row' form also grow - though not quite at the same rate as the ones in the main data table. But the text entry box remains the same size, however wide the column is:

![misaligned add new row section4](https://cloud.githubusercontent.com/assets/13660306/19514783/cde4200e-95ec-11e6-9f80-65266cdbefd0.PNG)

These screenshots were taken using Chrome. Firefox isn't quite as bad: there's still some misalignment, but not to the extent that text entry boxes can end up under the wrong column heading.

**Comment by scottbw** [comment]
For some reason the default CSS is different between the Mac and Windows editions of the same version of Chrome.

**Comment by scottbw** [comment]
I think I've managed to fix it - its behaving itself as far as I can tell on FF, Chrome (Mac) and Edge, Chrome (Win10) - I haven't got FF on windows.

**Comment by MerielP** [comment]
A slightly belated note to confirm that this is now working fine for me.
