### ISSUE TITLE
Right-most field names omitted in tables with lots of fields

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#42]
If you create a table with lots of field names (more than will fit on the screen without scrolling sideways) and view it in the Data Viewer, at first sight everything looks fine. Scrolling right, however, reveals that the in the section for adding new records, field names are missing for any fields that wouldn't fit within the original window:

![missing field names](https://cloud.githubusercontent.com/assets/13660306/18923659/0afd9ad6-85a5-11e6-93e2-50d48b4d1d47.PNG)

Once a record has been added to the table, things get even odder. The scroll bar for the portion of the screen containing existing records will now be active, and one can scroll right to see the rest of the fields - with their names, which have now magically appeared. However, the field names from the form for adding new records scroll along with the ones for existing records - independently of the boxes for adding data. This means one can end up with a new record form where the field names completely fail to match the fields underneath them.

![misaligned field names](https://cloud.githubusercontent.com/assets/13660306/18924056/a8f8b238-85a6-11e6-8adf-a9adbd967519.PNG)

**Comment by scottbw** [comment]
Aha, the scroll bars haven't been synced. I've fixed this now.
