### ISSUE TITLE
Field names in Data Viewer are sometimes misaligned

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#45]
Field names and the columns underneath them do not always align properly in the Data Viewer. Sometimes the result can be quite confusing - as in this example, where the primary key field overlaps with the 'Notes' field.

![misaligned field names 2](https://cloud.githubusercontent.com/assets/13660306/18925203/e58855ba-85aa-11e6-912d-652f1852cf85.PNG)

(I've seen examples where the misalignment is much more pronounced than this, but now I come to record this bug, I cannot find one to take a screenshot. It seems to vary, depending on the number of columns and the size of the window)

**Comment by scottbw** [comment]
I've made longer and shorter field names and content, and resized and zoomed and tried several browsers and I couldn't get it to appear with the overlapping field controls - which browser/OS combination were you using?

**Comment by MerielP** [comment]
This is using Chrome version 53.0.2785.116 m on Windows 7. 

Firefox v 49.0.1 is slightly better behaved (it's obvious which column the data is supposed to be in, even if things aren't perfectly aligned), but there's still some overlapping in the names:

![overlapping field names2](https://cloud.githubusercontent.com/assets/13660306/18926642/8986f6b2-85b0-11e6-94e6-f33a0fda05ba.PNG)

**Comment by MerielP** [comment]
The overlapping only happens when there's no space in the field name, by the way - otherwise it wraps:

![overlapping field names](https://cloud.githubusercontent.com/assets/13660306/18926793/1f75e566-85b1-11e6-94a0-671ea6edb1ec.PNG)

Very long names such as the above also seem to get truncated - although I suppose that's fair enough!

**Comment by scottbw** [comment]
Right, forced word breaks to deal with those long names full of underscores. Also faffed around with alignment to make things line up properly. Now the "add row" form doesn't line up with it. Argh.

![q3cug29](https://cloud.githubusercontent.com/assets/443092/18931030/6326d476-85c2-11e6-95f0-7483cfc76c4c.gif)

**Comment by scottbw** [comment]
Right! Sorted! (In Dev, we'll push a release up ASAP)

**Comment by MerielP** [comment]
Generally looks great now, but line breaks sometimes happen at odd points:

![field name line breaks](https://cloud.githubusercontent.com/assets/13660306/19037135/9f666066-896c-11e6-92bf-03bdcad298a6.PNG)

This looks particularly odd, as it looks as though the whole field name (artefact_description) could easily fit inside the column.

**Comment by scottbw** [comment]
Fixed - the inner column header divs weren't being allowed to fill the cell width (CSS again). Will close when released.

**Comment by scottbw** [comment]
Now in live

**Comment by MerielP** [comment]
Not sure whether this is just a result of work you're doing on resizing columns, but the misaligning problem seems to be back:

![more misaligned fields](https://cloud.githubusercontent.com/assets/13660306/19114411/c48f8832-8b05-11e6-8518-a69200cff235.PNG)

![more misaligned fields 2](https://cloud.githubusercontent.com/assets/13660306/19114416/c99f24a4-8b05-11e6-8690-8e86cb3cade0.PNG)

In the first table, the overlapping means the the down arrow for the drop-down list isn't visible, although one can still select by clicking on the list itself.

**Comment by scottbw** [comment]
Its not actually misaligning anything, its just that Firefox doesn't respect the box boundaries of cells and makes the textarea elements overlap. (It works fine on Chrome.)

**Comment by MerielP** [comment]
I get a similar problem in Chrome, I'm afraid:

![more misaligned fields 3](https://cloud.githubusercontent.com/assets/13660306/19116309/f4865938-8b0c-11e6-84eb-2f58fb382528.PNG)

![more misaligned fields 4](https://cloud.githubusercontent.com/assets/13660306/19116311/f9db14a0-8b0c-11e6-859d-5e87dc43d914.PNG)

**Comment by scottbw** [comment]
Fixed!
