### ISSUE TITLE
Capitalization of button text is inconsistent

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#46]
In ORDS1, the text on buttons was in sentence case (i.e. just the first letter of the first word capitalized, plus any proper nouns/acronyms). In ORDS2, newly added buttons are much more mixed: some in sentence case, some in title case (first letter of all words capitalized).

**Comment by scottbw** [comment]
The only offenders I've found so far are "Add New Row" and "Run Query" - these I've  just changed and will go into tomorrow's release.

**Comment by scottbw** [comment]
Now consistent on Live
