### ISSUE TITLE
No easy way back from Data Viewer to View, Edit, and Query Data page

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#47]
There doesn't seem to be a way (other than the browser's Back button) of getting from the Data Viewer back to the View, Edit, and Query Data page. If one is trying to switch rapidly between tables, this introduces an extra click.

**Comment by scottbw** [comment]
We could add another link in the breadcrumb trail e.g.

My projects > TestProject > TestDatabase > View, Edit and Query Data > Data Viewer

**Comment by scottbw** [comment]
Fixed in Dev
