### ISSUE TITLE
Changing field displayed in a linked field affects all linked fields in table

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#48]
When viewing a table in the Data Viewer, each linked field has a drop-down list which can be used to select a field to view the contents of.

Unfortunately, if a table contains multiple linked fields, selecting an option in one of them results in the contents of that field displaying in all linked fields across the table. In the example below, Author Name has been selected in the first linked field, but the author names are also displaying in the Journal Name field:

![linked fields](https://cloud.githubusercontent.com/assets/13660306/18926047/2b7b204a-85ae-11e6-83f4-e94fbea5fdfd.PNG)

Selecting an option from the Journal Name field also results in the contents of that field being replicated in the Author Name field.

**Comment by scottbw** [comment]
Fixed in dev; will close when released.

**Comment by scottbw** [comment]
Now in live.
