### ISSUE TITLE
Deleting a table doesn't trigger Save in schema designer

### ISSUE THREAD

**Issue by scottbw** [ox-it/ords-ui#49]
Related to other issues - need a review to make sure all SD actions trigger schema dirty state

**Comment by krispopat** [comment]
Yeah after some investigation, I think unsavedChanges is only being set on an xhr 201, so updates and deletes are not being caught. Am just working on a strategy to set dirty state in a more logical way.

**Comment by krispopat** [comment]
Fix committed to github

**Comment by krispopat** [comment]
On the server and ready to retest

**Comment by scottbw** [comment]
Works fine now.
