### ISSUE TITLE
Can't cancel the process of creating a new database

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#50]
If you click the 'Add new database' button, but then change your mind and click 'Cancel', the system won't let you leave the page until you've put something in the mandatory fields (database name and description). Once you've done this, you can click 'Cancel', but it doesn't actually cancel the database creation process - the new database gets created, just as if you'd clicked 'Add'.

**Comment by scottbw** [comment]
Fixed in dev

**Comment by scottbw** [comment]
Now in live

**Comment by MerielP** [comment]
I'm getting a weird residual buglet when I test this in Firefox (doesn't happen in Chrome; haven't tried other browsers).

I can now cancel the database creation process, but when I do, I get a small pop up message in the top left-hand corner of the screen, exhorting me to please fill in this field:

![cancel database message](https://cloud.githubusercontent.com/assets/13660306/19045328/1a8459e2-8990-11e6-96aa-5b7adae747a2.png)

Oddly, this isn't even the same as the message which appears when I try to create a database without completing the mandatory fields.
