### ISSUE TITLE
Temporary error when uploading CSV files

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#53]
If I upload a CSV file, and then immediately click 'View and edit database structure', the database schema is grey, and after a few seconds, an error message saying 'Internal problem while performing this action - please contact support." ' pops up (the double quotation mark at the end is in the message). The impression given is that there's a problem with the upload process.

However, if I exit the designer and go to the Data Viewer, everything seems to be fine: the table and its contents are there. If I then go back to the schema designer, the table is either now there, or appears after a few more moments.

I'm guessing that it's just taking a little while for the system to process the file and display the table in the schema designer, but this isn't obvious from a user's perspective: it looks like something has gone wrong.

This doesn't seem to happen with Access files - with those, I can view the database structure in the schema designer straightaway. However, I haven't tried uploading any particularly large files, so I don't know whether that would make a difference.

**Comment by scottbw** [comment]
I can't replicate this error so I assume it was fixed when Kris overhauled the upload process.
