### ISSUE TITLE
No easy way of editing queries

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#55]
In ORDS1, query results would appear in a separate tab from the query builder/SQL page. This meant that if one wanted to tweak the query, it was easy to go back to the other tab, make the desired changes, and then re-run the query.

In ORDS2, there seems to be no way of doing this: the only option is to return to the View, Edit, and Query Data page and re-enter the whole query. If it's a complex query, this may take a while - especially if you're new to SQL and it took you ages to get it (nearly) right in the first place.

Showing the results in a new tab isn't the only possible approach, but it would be nice to have some way of editing queries. For example, there could be an 'Edit query' button, which takes you back to the View, Edit, and Query Data page, but with the query you've just run still displaying.

**Comment by scottbw** [comment]
Yes, I'd noticed this myself and it is a pain. I think there should be some way to persist and restore the state of the query editor when its not in use - I'll investigate ...

**Comment by scottbw** [comment]
I've implemented something for this; it will keep queries between page views  or even if you log out and back in again. Visiting the Database Explorer for a different database clears the query. (In dev, will close when released)

**Comment by scottbw** [comment]
Released

**Comment by MerielP** [comment]
This is a definite improvement, but it's not terribly obvious from the query results page that you can do this - an 'Edit query' button would be useful addition. (A 'Clear query' button on the query page would also be a nice enhancement, though I think most people will probably be able to work out how to delete the query that's there!)

**Comment by scottbw** [comment]
I just sort of assumed someone would use the "back" button (which does work!) or the breadcrumb trail, but it can't hurt to stick a button on there too. (Though in general I think we have far too many buttons around the UI...)

**Comment by MerielP** [comment]
The back button does indeed work, and I suspect many people will just do that once they're familiar with the system - but I don't know how obvious it is to someone who's new to it.

(Just added issue #59 regarding clearing queries that are already there, as it's probably a slightly separate issue from this one.)

**Comment by scottbw** [comment]
Added "Edit query" button
