### ISSUE TITLE
No option to export query results as a CSV

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#56]
In ORDS1, all query results and datasets offered the option of exporting the results as a CSV file. For many researchers, this was a key piece of functionality, as they want to be able to import data from ORDS databases into other applications (for statistical analysis, for example, or to produce charts and graphs). It doesn't currently seem to be possible in ORDS2.

(ORDS1 didn't have this feature for public datasets viewed via the public search interface, but adding it there was on the wishlist for ages: if this could be done at the same time, that would be great.)

**Comment by scottbw** [comment]
Kris has been working on Export and should be pushing that live this week. 

It should be easy enough to export anything that displays in the data viewer (table,query results, dataset) as its basically all the same thing now.

**Comment by krispopat** [comment]
Export has now been implemented for tables, static views and query results.  This should appear in the next build.  I will close when this is out and you've had a chance to test.

**Comment by scottbw** [comment]
Functionality released - just need to add the export button to the public search view

**Comment by scottbw** [comment]
I've added the API button to the dataset search, and the Export button to the internal database explorer views and the data viewer for queries, datasets and tables.

**Comment by MerielP** [comment]
All seems to work beautifully. Two tiny niggles, however:
- There's a typo in the dialogue box that appears when you click the Export button. It says 'Please give you export file a name', instead of (presumably) 'Please give your export file a name' .
- I don't know if I would think to click a button labelled API to download a copy of the data (until I started working on ORDS, I had no idea what an API was, and suspect that will also be true for a lot of researchers). Would it maybe be worth relabelling the button as something like 'API and download'?

**Comment by scottbw** [comment]
Yes, I think "API" is there partly so we can go "look, its got an API!" when we demo, but in practice maybe a label like "Share" or "Get shareable links" would be better

**Comment by scottbw** [comment]
Fixed
