### ISSUE TITLE
Filtering of tables and query results works patchily

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#57]
In some cases, the filter interface seems to work fine. In others, it doesn't, though I haven't worked out exactly what the pattern is.

In one table (https://trunkdb.com/app/#/table/1206/1222/1246/MAIN/table/artefact_catalogue, created by uploading a CSV file), filtering with 'is' and 'is not' works fine, but 'contains' only works on the first two fields. I haven't managed to use 'like' to filter using wildcards: either it doesn't work at all, or it works like 'contains'.

If an attempt to filter doesn't work, the system just continues to display whatever was on the screen before (i.e. all records if no filter had been applied, or whatever subset had been selected by the last filter to work). In cases where it's not instantly obvious whether a filter has worked, this has the potential to be misleading.

Copy of the CSV file mentioned above, in case it's helpful: [artefact_catalogue.zip](https://github.com/ox-it/ords-ui/files/506604/artefact_catalogue.zip)

**Comment by scottbw** [comment]
To be honest I don't think the filter is working very well right now, and we may want to hide it until its been properly fixed.

**Comment by scottbw** [comment]
Full filter interface now restored on live
