### ISSUE TITLE
Field order is scrambled in visual query designer

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#58]
The order in which fields appear in the visual query designer bears no resemblance to that which they have elsewhere (e.g. in the schema designer or the data viewer). Nor does it appear to be alphabetical, or to follow any other obvious system.

In some cases, this is more noticeable than others:

![visual query designer field order](https://cloud.githubusercontent.com/assets/13660306/19043902/ebda4e36-8989-11e6-9220-1b161e369f30.PNG)

**Comment by scottbw** [comment]
Fixed in dev; I've used the same sort used in the Schema Designer, so if you order columns there, that should be reflected in the VQD.

**Comment by scottbw** [comment]
Released.
