### ISSUE TITLE
No easy way of clearing visual query designer

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#59]
When you build a query using the visual query designer to select tables and fields, the SQL appears in the query box at the bottom of the screen. If you've finished with one query and want to construct another one, you can delete the SQL - but the fields remain selected in the visual query designer. If you make any changes to what's selected, the designer assumes you want a query using everything that's still selected, and the SQL for this appears in the query box (overwriting anything you may have put there in the meantime).

If you've created a complex query involving lots of fields from lots of tables, going through and deselecting them all manually is fiddly and annoying. While it's useful for the selections to persist so that you can just do some tweaking rather than rebuilding the same query from scratch, it would also be useful to have a way of clearing all selections so you can start building something new.

Another nice feature along the same lines would be a select all/clear all check box for each table: this would be a big timesaver for some queries.

**Comment by scottbw** [comment]
Sounds like a very sensible addition

**Comment by scottbw** [comment]
Added a "Clear query" button so I'll close this issue - can you create a new one for adding the select all/clear all controls for tables?

**Comment by MerielP** [comment]
Cool - added issue #62 as requested.
