### ISSUE TITLE
Using 'Create foreign key button' freezes schema designer

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#60]
'Connect foreign key' now works for creating relationships between tables, but 'Create foreign key' still crashes things.

**Comment by krispopat** [comment]
Yes, this was using the wrong rest call, a left over from a previous iteration of the REST api.  Have fixed and will commit.

**Comment by krispopat** [comment]
Fix committed to github

**Comment by krispopat** [comment]
On the server and ready to retest

**Comment by scottbw** [comment]
Tested - works OK.
