### ISSUE TITLE
Can't add new records if a table contains two or more linked fields referencing the same table

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#61]
Sometimes you want to be able to create a table where two or more linked fields point to entries in the same table. For example, this table is designed to show family relationships, by linking to records in a table that lists people:

![more misaligned fields](https://cloud.githubusercontent.com/assets/13660306/19114968/1d0b6e3e-8b08-11e6-9f39-62f1f07f01b0.PNG)

However, while the schema designer will let you create tables linked in this way, you can't then add records to them. You don't get an error message: the 'Add new row' button just doesn't do anything.

**Comment by scottbw** [comment]
OK, I know what causes this, should be easy enough to fix

**Comment by scottbw** [comment]
Fixed
