### ISSUE TITLE
Notifications sometimes get hidden

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#63]
The system displays a lot of notifications in the top right-hand corner of the screen, to show whether something has been successful or not. In a few situations, these can end up getting partially hidden behind other things on the screen.

I've noticed this in two places:

In the visual query designer, if you scroll down the page so that the area where the tables appear is at the top of the window:

![partially hidden notification](https://cloud.githubusercontent.com/assets/13660306/19307581/22545516-9073-11e6-98fc-26f6545769fc.PNG)

And in the schema designer:

![partially hidden notification2](https://cloud.githubusercontent.com/assets/13660306/19307588/2cd78e54-9073-11e6-8b0d-75a16976f8db.PNG)

**Comment by scottbw** [comment]
Sorted - z-index wasn't set high enough

**Comment by scottbw** [comment]
In live now, ready to retest

**Comment by MerielP** [comment]
All seems to be behaving as it should now.
