### ISSUE TITLE
Query results falsely claim to be displaying records from #2 onwards

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#64]
When you run a query, the system claims to be displaying 'Records #:2 to N of N', and helpfully provides a 'Previous' button, presumably to allow you to go back and see the first record. Except that in fact, the first record is already being displayed, as in this case, where records 1 to 10 are all present and correct:

![error in record count](https://cloud.githubusercontent.com/assets/13660306/19307940/12e2b378-9075-11e6-93f1-5d43661b0988.PNG)

If you click the 'Previous' button, it disappears, and the record count corrects itself to say 'Records #:1 to N of N. As far as I can tell, the records displayed remain unchanged:

![corrected record count](https://cloud.githubusercontent.com/assets/13660306/19307989/4dacffc2-9075-11e6-937f-3f1efb94510e.PNG)

**Comment by scottbw** [comment]
Yes, there is some mismatch going on with the pagination.

**Comment by scottbw** [comment]
Found it - when converting the requested starting row to an offset, the calculation is performed _twice_. So "next" should return rows 51-100, it returns startRow=51 (as this is calculated once), but actually returns 50-99.

**Comment by scottbw** [comment]
Right, ready to retest.

**Comment by MerielP** [comment]
Yep - all seems to be working fine now.
