### ISSUE TITLE
Possible to resize the visual query designer table area off the edge of the screen

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#65]
The area that displays the tables in the visual query designer can be resized as desired. If you make it longer, the shaded area which contains it grows to accommodate it (and everything below it on the page moves down). However, if you make it wider, it escapes from the shaded area:

![resized table area](https://cloud.githubusercontent.com/assets/13660306/19310289/43b730b2-9081-11e6-8365-1989a50520ba.PNG)

As far as I can tell, this doesn't cause any problems in terms of the functionality of the query designer - but it does look a bit odd.

**Comment by scottbw** [comment]
I'll disable horizontal resizing to stop this happening.

**Comment by scottbw** [comment]
Fixed.
