### ISSUE TITLE
Data editing interface should allow several records to be edited at once

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords-ui#7]
At present, the only way to edit a record is to click on the pencil icon next to that record. The original version was more flexible, as it permitted users to edit the data directly in the tabular view. A user could edit multiple cells, with each cell being highlighted in light blue to indicate its contents had been edited. To save the edited data, the user could press <enter> or click the 'Save Changes' button below the tabular view. This was quicker and easier than editing the data one record at a time, and should be reinstated if possible.

**Comment by krispopat** [comment]
Update on server for checking.

**Comment by scottbw** [comment]
Fixed.
