### ISSUE TITLE
Visual query designer not working in Chrome (on Windows 7)

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#72]
The visual query designer has stopped working for me in Chrome (using Windows 7). Tables still appear when I select them, but when I select fields, no SQL appears in the query box, and I can't add anything using the constraint editor.

I can type SQL into the query box and run a query that way, but if I use the 'Edit query' button, the query has disappeared when I get back to the View, Edit, and Query Data page.

Firefox seems fine.

**Comment by scottbw** [comment]
I've tried it with Chrome on Windows 10 and it works fine there. I wonder if there's an issue with the browser state (it saves your previous settings in the browser storage, which is how it remembers them - its possible its getting an error when it reloads them)

Can you get a screen capture of the JavaScript console in case there's an error report there?

**Comment by MerielP** [comment]
This is the screen with the console:

![visual query designer error](https://cloud.githubusercontent.com/assets/13660306/19593408/57866c18-9778-11e6-9430-ea4773679781.PNG)

And for better readability, here's just the console:

![javascript console](https://cloud.githubusercontent.com/assets/13660306/19593434/753db43c-9778-11e6-84b6-28d3606f46a1.PNG)

**Comment by scottbw** [comment]
As I suspected, it was just you had a saved query state from before we rolled out the update so it wasn't initialised correctly. I've put a fix in for this - refresh the browser and it should be fine now.
