### ISSUE TITLE
Data editing interface: choice of field displayed from linked table resets whenever screen refreshed

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords-ui#8]
It is important that when users are editing data, the information displayed in a field that links to another table displays the data from the most meaningful field in that linked table - which usually isn't the default primary key ID. The original ORDS retained the knowledge of which field the user had selected so that when data was updated and the screen refreshed, linked fields did not revert to the default primary key. It would be good to reinstate this.

**Comment by scottbw** [comment]
I've checked in an implementation for this using localStorage into Dev.
